/*
 * TMSB Overlay
 * Copyright (C) 2026 Haley "Thin Mint" Stelly
 *
 * This file is an original work (not derived from CRG Scoreboard).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * See LICENSE and NOTICE for full details.
 */
/**
 * TMSB Overlay — CRG connection loader
 *
 * Load this file synchronously (via a plain <script src="loader.js"> tag)
 * after config.js. It must run before the page body is parsed.
 *
 * Responsibilities:
 *   1. Merge TMSB_CONFIG defaults with any localStorage overrides set
 *      by the Admin panel.
 *   2. Emit a console warning if the page is opened via file:// with no
 *      CRG host configured (jQuery will likely fail to load).
 *   3. Patch window.WebSocket to redirect connections to the configured
 *      CRG host, and fire tmsb:wsconnected / tmsb:wsdisconnected events
 *      so the overlay and admin can react to mid-bout disconnections.
 *   4. Install a window.WS stub that queues WS.Register() / WS.Set() /
 *      WS.AfterLoad() calls made before core.js arrives and replays them
 *      on the real WS object once it loads.
 *   5+6. Load jQuery, then core.js in jQuery's onload callback. This
 *      guarantees core.js never runs before jQuery is ready, regardless of
 *      how the host browser handles external script loading (including OBS).
 *      jQuery is loaded from the remote CRG host when a remote is configured
 *      or the page is opened via file://; otherwise from the local CRG path.
 *      core.js is cache-busted with a timestamp query string.
 *      Dispatches tmsb:crgready on success or tmsb:crgfailed on failure.
 */
(function () {

  /* ── 0. Seed localStorage from URL query params ───────────────────────
     Allows a pre-configured overlay URL (e.g. generated by the Admin panel's
     "Copy Link" button) to bootstrap any browser — Chrome, OBS, a fresh
     Firefox profile — without manual Admin panel setup on each client.
     Values written here are immediately visible to step 1's waterfall.
  ─────────────────────────────────────────────────────────────────────── */
  try {
    if (typeof URLSearchParams !== 'undefined' && window.location.search) {
      var _up = new URLSearchParams(window.location.search);
      if (_up.get('crg_ip'))      { localStorage.setItem('tmsb_crg_ip',      _up.get('crg_ip'));      }
      if (_up.get('crg_port'))    { localStorage.setItem('tmsb_crg_port',    _up.get('crg_port'));    }
      if (_up.get('crg_timeout')) { localStorage.setItem('tmsb_crg_timeout', _up.get('crg_timeout')); }
    }
  } catch (e) { /* localStorage may be unavailable in sandboxed iframes */ }

  /* ── 1. Configuration ─────────────────────────────────────────────────── */
  var cfg     = window.TMSB_CONFIG || {};
  var ip      = localStorage.getItem('tmsb_crg_ip')
             || cfg.CRG_IP
             || localStorage.getItem('tmsb_last_crg_ip')  // last IP that successfully connected
             || window.location.hostname;
  var port    = localStorage.getItem('tmsb_crg_port') || cfg.CRG_PORT    || window.location.port || '8000';
  var timeout = parseInt(localStorage.getItem('tmsb_crg_timeout') || cfg.TIMEOUT_MS || 5000, 10);

  // Expose resolved values for status displays and error messages.
  window._TMSB_CRG_BASE   = 'http://' + ip + ':' + port;
  window._TMSB_TIMEOUT_MS = timeout;

  /* ── 2. file:// warning ───────────────────────────────────────────────── */
  // When opened via file:// with a remote host configured, jQuery and
  // core.js both load from the remote CRG host — this is the intended
  // workflow for a standalone overlay computer.
  // Warn only if file:// is used with no remote configured, since there
  // is no CRG instance to load from in that case.
  if (window.location.protocol === 'file:' &&
      !localStorage.getItem('tmsb_crg_ip') && !cfg.CRG_IP &&
      !localStorage.getItem('tmsb_last_crg_ip')) {
    console.warn(
      '[TMSB] Page opened via file:// with no CRG host configured. ' +
      'Set CRG_IP in config.js or use the Admin panel \u2192 CRG Connection ' +
      'to point at a running CRG instance before the overlay will work.'
    );
  }

  /* ── 3. WebSocket patch ───────────────────────────────────────────────── */
  var wsTarget = ip + ':' + port;
  var _OrigWS  = window.WebSocket;

  function PatchedWS(url, protocols) {
    var redirected = url.replace(/^(wss?:\/\/)[^\/]+/, '$1' + wsTarget);
    var ws         = protocols
      ? new _OrigWS(redirected, protocols)
      : new _OrigWS(redirected);

    ws.addEventListener('open', function () {
      window._TMSB_WS_CONNECTED = true;
      // Persist the IP that just successfully connected. This survives
      // admin panel resets and CRG restarts, giving file:// browsers a
      // last-known-good fallback without any operator action.
      try { localStorage.setItem('tmsb_last_crg_ip', ip); } catch (e) {}
      document.dispatchEvent(new CustomEvent('tmsb:wsconnected'));
    });
    ws.addEventListener('close', function () {
      window._TMSB_WS_CONNECTED = false;
      document.dispatchEvent(new CustomEvent('tmsb:wsdisconnected'));
    });

    // Returning a non-primitive from a constructor causes `new` to return
    // that value instead of `this`, so callers get the real WS instance.
    return ws;
  }
  PatchedWS.prototype  = _OrigWS.prototype;
  PatchedWS.CONNECTING = _OrigWS.CONNECTING;
  PatchedWS.OPEN       = _OrigWS.OPEN;
  PatchedWS.CLOSING    = _OrigWS.CLOSING;
  PatchedWS.CLOSED     = _OrigWS.CLOSED;
  window.WebSocket     = PatchedWS;

  /* ── 4. WS stub ───────────────────────────────────────────────────────── */
  // Absorbs WS.Register() / WS.Set() / WS.AfterLoad() calls made by the
  // overlay's own scripts while core.js is still in flight.  When core.js
  // eventually sets window.WS = <real object>, the setter replays them.
  var _stub = {
    _queue: [], _real: null,
    Register : function () { this._queue.push(['Register',  Array.prototype.slice.call(arguments)]); },
    Set      : function () { this._queue.push(['Set',       Array.prototype.slice.call(arguments)]); },
    AfterLoad: function () { this._queue.push(['AfterLoad', Array.prototype.slice.call(arguments)]); },
    state    : {}
  };
  try {
    Object.defineProperty(window, 'WS', {
      configurable: true,
      get: function ()  { return _stub._real || _stub; },
      set: function (v) {
        _stub._real = v;
        _stub._queue.forEach(function (c) {
          if (typeof v[c[0]] === 'function') { v[c[0]].apply(v, c[1]); }
        });
        _stub._queue = [];
      }
    });
  } catch (e) {
    // Fallback for environments where defineProperty on window is restricted.
    window.WS = _stub;
  }

  /* ── 5 + 6. Load jQuery then core.js in sequence ─────────────────────── */
  // We chain the loads: jQuery first, then core.js in jQuery's onload.
  // This guarantees jQuery is fully available before core.js executes,
  // regardless of how the host browser (including OBS's embedded Chromium)
  // handles script loading. document.write is intentionally avoided as it
  // behaves inconsistently inside external script files in some environments.

  var _remoteConfigured = !!(localStorage.getItem('tmsb_crg_ip') || cfg.CRG_IP);
  var _jquerySrc = (_remoteConfigured || window.location.protocol === 'file:')
    ? window._TMSB_CRG_BASE + '/external/jquery/jquery.js'
    : '/external/jquery/jquery.js';

  var done = false;

  function markFailed(reason) {
    if (done) { return; }
    done = true;
    window.CRG_OFFLINE = reason;
    document.dispatchEvent(new CustomEvent('tmsb:crgfailed', { detail: { reason: reason } }));
  }

  function loadCoreJs() {
    var timer = setTimeout(function () { markFailed('timeout'); }, timeout);

    var core   = document.createElement('script');
    core.src     = window._TMSB_CRG_BASE + '/json/core.js?v=' + Date.now();
    core.onload  = function () {
      if (!done) {
        done = true;
        clearTimeout(timer);
        document.dispatchEvent(new CustomEvent('tmsb:crgready'));
      }
    };
    core.onerror = function () { clearTimeout(timer); markFailed('error'); };
    document.head.appendChild(core);
  }

  var jquery = document.createElement('script');
  jquery.src    = _jquerySrc;
  jquery.onload = loadCoreJs;
  jquery.onerror = function () { markFailed('error'); };
  document.head.appendChild(jquery);

})();
